spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/petshop?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: root
